
// Generated by Devices Lab https://deviceslab.org
import type { ResearchType } from "$lib/data/data";

export const research: ResearchType = {
    "key": "circuitglue-sh3p4b",
    "doi": "10.1145/3596265",
    "type": "Research Paper",
    "name": "CircuitGlue",
    "title": "CircuitGlue: A Software Configurable Converter for Interconnecting Multiple Heterogeneous Electronic Components",
    "abstract": "CircuitGlue is an electronic prototyping board that facilitates the connection of various off-the-shelf electronic components and modules. The board's input header is software-configurable, allowing modules to be instantly compatible regardless of differences in voltage levels, interface types, communication protocols, and pinouts.",
    "authors": [
        {
            "name": "Mannu Lambrichts",
            "affiliation": "Hasselt University - Flanders Make - Expertise Centre for Digital Media, Diepenbeek, Belgium"
        },
        {
            "name": "Raf Ramakers",
            "affiliation": "Hasselt University - Flanders Make - Expertise Centre for Digital Media, Diepenbeek, Belgium"
        },
        {
            "name": "Steve Hodges",
            "affiliation": "Microsoft Research, Cambridge, United Kingdom"
        },
        {
            "name": "James Devine",
            "affiliation": "Microsoft Research, Cambridge, United Kingdom"
        },
        {
            "name": "Lorraine Underwood",
            "affiliation": "Lancaster University, Lancaster, United Kingdom"
        },
        {
            "name": "Joe Finney",
            "affiliation": "Lancaster University, Lancaster, United Kingdom"
        }
    ],
    "published": {
        "year": 2023,
        "month": 6,
        "day": 12
    },
    "conference": "Proceedings of the ACM on Interactive, Mobile, Wearable and Ubiquitous Technologies",
    "conferenceShort": "IMWUT '23",
    "location": "Cancún, Mexico",
    "links": [
        {
            "text": "DOI Link",
            "href": "https://doi.org/10.1145/3596265",
            "icon": "ScrollText"
        },
        {
            "text": "YouTube",
            "icon": "Youtube",
            "href": "https://youtu.be/tNl2-hSjy74"
        },
        {
            "text": "GitHub",
            "icon": "Github",
            "href": "https://github.com/MannuLambrichts/CircuitGlue"
        }
    ],
    "tags": [
        {
            "name": "prototyping"
        },
        {
            "name": "hardware"
        },
        {
            "name": "circuitglue"
        }
    ],
    "awards": []
};
