
// Generated by Devices Lab https://deviceslab.org
import type { ResearchType } from "$lib/data/research";

export const research: ResearchType = {
    "doi": "10.1145/3585088.3593897",
    "type": "Research Paper",
    "name": "clip-bit",
    "title": "Supporting fieldwork for primary education with computing - micro:bit, clip:bit and game controllers",
    "abstract": "",
    "authors": [
        {
            "name": "Elizabeth Edwards",
            "affiliation": "Lancaster University, United Kingdom"
        },
        {
            "name": "John Edward Vidler",
            "affiliation": "Computing and Communications, Lancaster University, United Kingdom"
        },
        {
            "name": "Lorraine Underwood",
            "affiliation": "School of Computing and Communications, Lancaster University, United Kingdom"
        },
        {
            "name": "Elisa Rubegni",
            "affiliation": "Lancaster University, United Kingdom"
        },
        {
            "name": "Joe Finney",
            "affiliation": "School of Computing and Communications, Lancaster University, United Kingdom"
        }
    ],
    "published": {
        "year": 2023,
        "month": 6,
        "day": 19
    },
    "conference": "Proceedings of the 22nd Annual ACM Interaction Design and Children Conference",
    "location": "",
    "links": [
        {
            "text": "DOI Link",
            "href": "https://doi.org/10.1145/3585088.3593897",
            "icon": "ScrollText"
        }
    ],
    "tags": [],
    "awards": []
};
