
// Generated by Devices Lab https://deviceslab.org
import type { ResearchType } from "$lib/data/research";

export const research: ResearchType = {
    "doi": "10.1145/3585088.3593897",
    "type": "Poster",
    "name": "clip-bit",
    "title": "Connecting primary-aged children to place through teaching data science with physical computing tools",
    "abstract": "",
    "authors": [
        {
            "name": "Lorraine Underwood",
            "affiliation": "Lancaster University, United Kingdom"
        },
        {
            "name": "John Edward Vidler",
            "affiliation": "Computing and Communications, Lancaster University, United Kingdom"
        },
        {
            "name": "Richard Harper",
            "affiliation": ""
        },
        {
            "name": "Liz Edwards",
            "affiliation": ""
        },
        {
            "name": "Joe Finney",
            "affiliation": ""
        },
        {
            "name": "Elisa Rubegni",
            "affiliation": ""
        },
        {
            "name": "Steve Hodges",
            "affiliation": ""
        }
    ],
    "published": {
        "year": 0,
        "month": 0,
        "day": 0
    },
    "conference": "",
    "location": "",
    "links": [
        {
            "text": "PDF",
            "href": "https://www.devices-lab.org/wp-content/uploads/2024/07/digitaleconomies_cloudletposter.pdf",
            "icon": "Paperclip"
        }
    ],
    "tags": [],
    "awards": []
};
