// Generated by Devices Lab https://deviceslab.org
import type { Publication } from '$lib/data/data';

export const research: Publication = {
	key: 'logicglue--imz83s',
	doi: '10.1145/3735498',
	type: 'Research Paper',
	name: 'LogicGlue',
	title: 'LogicGlue: Hardware-Independent Embedded Programming Through Platform-Independent Drivers',
	abstract: 'LogicGlue is a platform-independent driver system that decouples application logic from hardware specifics, enabling embedded programs to run across different microcontrollers without modification. It preserves native component features and protocols, simplifying prototyping while maintaining flexibility in hardware choice.',
	authors: [
		{
			name: 'Mannu Lambrichts',
			affiliation: 'School of Computing and Communications'
		},
		{
			name: 'Raf Ramakers',
			affiliation: 'Digital Future Lab'
		},
		{
			name: 'Steve Hodges',
			affiliation: 'School of Computing and Communications'
		}
	],
	published: {
		year: 2025,
		month: 6,
		day: 27
	},
	conference: 'Proceedings of the 17th ACM International Conference on Engineering Interactive Computing Systems',
	conferenceShort: "EICS '25",
	location: 'Trier, Germany',
	links: [
		{
			text: 'DOI Link',
			href: 'https://doi.org/10.1145/3735498',
			icon: 'ScrollText'
		}
	],
	tags: [],
	awards: []
};
