
// Generated by Devices Lab https://deviceslab.org
import type { Publication } from "$lib/data/data";

export const research: Publication = {
	"key": "makedevice--nwzdqd",
    "doi": "10.1145/3569009.3573106",
    "type": "Research Paper",
    "name": "MakeDevice",
    "title": "MakeDevice: Evolving Devices Beyond the Prototype with Jacdac",
    "abstract": "MakeDevice abstract todo",
    "authors": [
        {
            "name": "Kobi Hartley",
            "affiliation": "School of Computing and Communications, Lancaster University, United Kingdom"
        },
        {
            "name": "Joe Finney",
            "affiliation": "School of Computing and Communications, Lancaster University, United Kingdom"
        },
        {
            "name": "Steve Hodges",
            "affiliation": "Microsoft Research, United Kingdom"
        },
        {
            "name": "Peli De Halleux",
            "affiliation": "Microsoft Research, United States"
        },
        {
            "name": "James Devine",
            "affiliation": "Microsoft, United Kingdom"
        },
        {
            "name": "Gabriele D'Amone",
            "affiliation": "Microsoft, United Kingdom"
        }
    ],
    "published": {
        "year": 2023,
        "month": 2,
        "day": 26
    },
    "conference": "Proceedings of the 17th International Conference on Tangible, Embedded, and Embodied Interaction",
	"conferenceShort": "TEI '23",
    "location": "",
    "links": [
        {
            "text": "DOI Link",
            "href": "https://doi.org/10.1145/3569009.3573106",
            "icon": "ScrollText"
        }
    ],
    "tags": [],
    "awards": []
};
