
// Generated by Devices Lab https://deviceslab.org
import type { Publication } from "$lib/data/data";

export const research: Publication = {
	"key": "test-1jsmq",
    "doi": "",
    "type": "",
    "name": "Test",
    "title": "Test",
    "abstract": "This is a test to demonstrate the supported richtext options:\nBold: ${bold}[bold]\nItalic: ${italic}[italic]\nUnderline: ${underline}[underline]\nHighlight: ${highlight}[highlight]\nCode: ${code}[code]\nOCR font: ${ocr}[OCR font]\nIcons: ${icon name=Dog} ${icon name=Cat}\nInternal links: ${link href='/solder-bit/gamepad'}[solderbit gamepad] \nExternal links: ${link href='https://www.google.com'}[click me!] \n${br}\n${hr}\n${link href='test'}[test]\nThis is a ${span class='link-red'}[span] with a different color.",
    "authors": [],
    "published": {
        "year": 0,
        "month": 0,
        "day": 0
    },
    "conference": "",
	"conferenceShort": "",
    "location": "",
    "links": [],
    "tags": [],
    "awards": [{name: "Test Award", icon: "Trophy"}],
};
