
// Generated by Devices Lab https://deviceslab.org
import type { ResearchType } from "$lib/data/research";

export const research: ResearchType = {
    "doi": "10.1145/3463523",
	"type": "Research Paper",
    "name": "Toolkit Classification",
    "title": "A Survey and Taxonomy of Electronics Toolkits for Interactive and Ubiquitous Device Prototyping",
    "abstract": "Over the past two decades, many toolkits for prototyping interactive and ubiquitous electronic devices have been developed. Although their technical specifications are often easy to look up, they vary greatly in terms of design, features and target audience, resulting in very real strengths and weaknesses depending on the intended application. These less technical characteristics are often reported inconsistently, if at all. In this paper we provide a comprehensive survey of interactive and ubiquitous device prototyping toolkits, systematically analysing their characteristics within the framework of a new taxonomy that we present. In addition to the specific characteristics we cover, we introduce a way to evaluate toolkits more holistically, covering user needs such as 'ease of construction' and 'ease of moving from prototype to product' rather than features. We also present results from an online survey which offers new insights on how the surveyed users prioritize these characteristics during prototyping, and what techniques they use to move beyond prototyping. We hope our analysis will be valuable for others in the community who need to build and potentially scale out prototypes as part of their research. We end by identifying gaps that have not yet been addressed by existing offerings and discuss opportunities for future research into electronics prototyping toolkits.",
    "authors": [
        {
            "name": "Mannu Lambrichts",
            "affiliation": "Hasselt University - tUL - Flanders Make - Expertise Centre for Digital Media, BE"
        },
        {
            "name": "Raf Ramakers",
            "affiliation": "Hasselt University - tUL - Flanders Make - Expertise Centre for Digital Media, BE"
        },
        {
            "name": "Steve Hodges",
            "affiliation": "Microsoft Research, Cambridge, UK"
        },
        {
            "name": "Sven Coppers",
            "affiliation": "Hasselt University - tUL - Flanders Make - Expertise Centre for Digital Media, BE"
        },
        {
            "name": "James Devine",
            "affiliation": "Microsoft Research, Cambridge, UK"
        }
    ],
    "published": {
        "year": 2021,
        "month": 6,
        "day": 23
    },
    "conference": "Proc. ACM Interact. Mob. Wearable Ubiquitous Technol.",
    "location": "Remote",
    "links": [
        {
            "text": "DOI Link",
            "href": "https://doi.org/10.1145/3463523",
            "icon": "ScrollText"
        }
    ],
    "tags": [],
    "awards": []
};
